### ISSUE TITLE
木有 settings.yaml

### ISSUE THREAD

**Issue by ruibaby** [LIlGG/halo-live2d#1]
我看到 live2d.ftl 里面有很多主题设置项 https://github.com/LIlGG/halo-live2d/blob/master/live2d/ftl/live2d.ftl#L23-L59

那么是否需要提供一下 settings.yaml 呢。

**Comment by LIlGG** [comment]
实际上我本身是想提供一个API文档，然后由主题开发者或者用户自行配置，因为这些内容我都设置了默认值，正常情况下不需要配置就可以使用。
但或许对于用户而言，直接提供一个settings.yaml更好。
稍晚一会儿我会提供一份settings.yaml

**Comment by ruibaby** [comment]
> 实际上我本身是想提供一个API文档，然后由主题开发者或者用户自行配置，因为这些内容我都设置了默认值，正常情况下不需要配置就可以使用。
> 
> 但或许对于用户而言，直接提供一个settings.yaml更好。
> 
> 稍晚一会儿我会提供一份settings.yaml

太帅啦～ 另外不得不夸一句那个评论组件做的太棒啦👍 。忙过这阵打算邀请你进入 halo-dev，如果你愿意的话。

**Comment by LIlGG** [comment]
> > 实际上我本身是想提供一个API文档，然后由主题开发者或者用户自行配置，因为这些内容我都设置了默认值，正常情况下不需要配置就可以使用。
> > 但或许对于用户而言，直接提供一个settings.yaml更好。
> > 稍晚一会儿我会提供一份settings.yaml
> 
> 太帅啦～ 另外不得不夸一句那个评论组件做的太棒啦👍 。忙过这阵打算邀请你进入 halo-dev，如果你愿意的话。

非常感谢大佬的赏识 能进入halo-dev和大佬们交流是我的荣幸，怎么可能不愿意。 我会尽全力来帮助halo的维护和开发 ！
